-- Compiled by Swept for GTNH 2.7.3 in 2025

return {
	gluon = {
		{ Name = "gregtech:gt.metaitem.01", ID = 2086, Label = "Gold Dust", Plasma = "{Fluid:plasma.gold}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 3, Label = "Zirconium Dust", Plasma = "{Fluid:plasma.zirconium}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 64, Label = "Ruthenium Dust", Plasma = "{Fluid:plasma.ruthenium}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 78, Label = "Rhodium Dust", Plasma = "{Fluid:plasma.rhodium}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 11012, Label = "Iodine Dust", Plasma = "{Fluid:plasma.iodine}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2008, Label = "Beryllium Dust", Plasma = "{Fluid:plasma.beryllium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2010, Label = "Carbon Dust", Plasma = "{Fluid:plasma.carbon}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2017, Label = "Sodium Dust", Plasma = "{Fluid:plasma.sodium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2018, Label = "Magnesium Dust", Plasma = "{Fluid:plasma.magnesium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2019, Label = "Aluminium Dust", Plasma = "{Fluid:plasma.aluminium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2020, Label = "Raw Silicon Dust", Plasma = "{Fluid:plasma.silicon}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2025, Label = "Potassium Dust", Plasma = "{Fluid:plasma.potassium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2028, Label = "Titanium Dust", Plasma = "{Fluid:plasma.titanium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2029, Label = "Vanadium Dust", Plasma = "{Fluid:plasma.vanadium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2031, Label = "Manganese Dust", Plasma = "{Fluid:plasma.manganese}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2033, Label = "Cobalt Dust", Plasma = "{Fluid:plasma.cobalt}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2037, Label = "Gallium Dust", Plasma = "{Fluid:plasma.gallium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2039, Label = "Arsenic Dust", Plasma = "{Fluid:plasma.arsenic}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2043, Label = "Rubidium Dust", Plasma = "{Fluid:plasma.rubidium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2044, Label = "Strontium Dust", Plasma = "{Fluid:plasma.strontium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2045, Label = "Yttrium Dust", Plasma = "{Fluid:plasma.yttrium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2048, Label = "Molybdenum Dust", Plasma = "{Fluid:plasma.molybdenum}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2052, Label = "Palladium Dust", Plasma = "{Fluid:plasma.palladium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2055, Label = "Cadmium Dust", Plasma = "{Fluid:plasma.cadmium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2056, Label = "Indium Dust", Plasma = "{Fluid:plasma.indium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2058, Label = "Antimony Dust", Plasma = "{Fluid:plasma.antimony}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2059, Label = "Tellurium Dust", Plasma = "{Fluid:plasma.tellurium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2062, Label = "Caesium Dust", Plasma = "{Fluid:plasma.caesium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2063, Label = "Barium Dust", Plasma = "{Fluid:plasma.barium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2064, Label = "Lanthanum Dust", Plasma = "{Fluid:plasma.lanthanum}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2065, Label = "Cerium Dust", Plasma = "{Fluid:plasma.cerium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2066, Label = "Praseodymium Dust", Plasma = "{Fluid:plasma.praseodymium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2067, Label = "Neodymium Dust", Plasma = "{Fluid:plasma.neodymium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2068, Label = "Promethium Dust", Plasma = "{Fluid:plasma.promethium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2069, Label = "Samarium Dust", Plasma = "{Fluid:plasma.samarium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2070, Label = "Europium Dust", Plasma = "{Fluid:plasma.europium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2071, Label = "Gadolinium Dust", Plasma = "{Fluid:plasma.gadolinium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2072, Label = "Terbium Dust", Plasma = "{Fluid:plasma.terbium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2073, Label = "Dysprosium Dust", Plasma = "{Fluid:plasma.dysprosium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2074, Label = "Holmium Dust", Plasma = "{Fluid:plasma.holmium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2075, Label = "Erbium Dust", Plasma = "{Fluid:plasma.erbium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2076, Label = "Thulium Dust", Plasma = "{Fluid:plasma.thulium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2077, Label = "Ytterbium Dust", Plasma = "{Fluid:plasma.ytterbium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2080, Label = "Tantalum Dust", Plasma = "{Fluid:plasma.tantalum}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2081, Label = "Tungsten Dust", Plasma = "{Fluid:plasma.tungsten}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2097, Label = "Uranium 235 Dust", Plasma = "{Fluid:plasma.uranium235}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2098, Label = "Uranium 238 Dust", Plasma = "{Fluid:plasma.uranium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2382, Label = "Ardite Dust", Plasma = "{Fluid:plasma.ardite}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2393, Label = "Oriharukon Dust", Plasma = "{Fluid:plasma.oriharukon}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2884, Label = "Desh Dust", Plasma = "{Fluid:plasma.desh}" },
		{ Name = "miscutils:itemDustGermanium", ID = 0, Label = "Germanium Dust", Plasma = "{Fluid:plasma.germanium}" },
		{ Name = "miscutils:itemDustThallium", ID = 0, Label = "Thallium Dust", Plasma = "{Fluid:plasma.thallium}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 30, Label = "Thorium 232 Dust", Plasma = "{Fluid:plasma.thorium232}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2021, Label = "Phosphorus Dust", Plasma = "{Fluid:plasma.phosphorus}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2032, Label = "Iron Dust", Plasma = "{Fluid:plasma.iron}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2006, Label = "Lithium Dust", Plasma = "{Fluid:plasma.lithium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2340, Label = "Meteoric Iron Dust", Plasma = "{Fluid:plasma.meteoriciron}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2078, Label = "Lutetium Dust", Plasma = "{Fluid:plasma.lutetium}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2036, Label = "Zinc Dust", Plasma = "{Fluid:plasma.zinc}" },
		{ Name = "bartworks:gt.bwMetaGenerateddust", ID = 11000, Label = "Hafnium Dust", Plasma = "{Fluid:plasma.hafnium}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2026, Label = "Calcium Dust", Plasma = "{Fluid:plasma.calcium}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2103, Label = "Americium Dust", Plasma = "{Fluid:plasma.americium}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2047, Label = "Niobium Dust", Plasma = "{Fluid:plasma.niobium}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2022, Label = "Sulfur Dust", Plasma = "{Fluid:plasma.sulfur}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2054, Label = "Silver Dust", Plasma = "{Fluid:plasma.silver}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2057, Label = "Tin Dust", Plasma = "{Fluid:plasma.tin}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2035, Label = "Copper Dust", Plasma = "{Fluid:plasma.copper}" },
	--    { Name = "gregtech:gt.metaitem.01", ID = 2034, Label = "Nickel Dust", Plasma = "{Fluid:plasma.nickel}" },
	},

	magmatter = {
		{ Name = "gregtech:gt.metaitem.01", ID = 2397, Label = "Infinity Dust", Plasma = "{Fluid:plasma.infinity}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2329, Label = "Tritanium Dust", Plasma = "{Fluid:plasma.tritanium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2982, Label = "Cosmic Neutronium Dust", Plasma = "{Fluid:plasma.cosmicneutronium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2976, Label = "Awakened Draconium Dust", Plasma = "{Fluid:plasma.draconiumawakened}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2395, Label = "Bedrockium Dust", Plasma = "{Fluid:plasma.bedrockium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2984, Label = "Flerovium Dust", Plasma = "{Fluid:plasma.flerovium_gt5u}" },
		{ Name = "DraconicEvolution:draconiumDust", ID = 0, Label = "Draconium Dust", Plasma = "{Fluid:plasma.draconium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2129, Label = "Neutronium Dust", Plasma = "{Fluid:plasma.neutronium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2978, Label = "Ichorium Dust", Plasma = "{Fluid:plasma.ichorium}" },
		{ Name = "gregtech:gt.metaitem.01", ID = 2978, Label = "Six-Phased Copper Dust", Plasma = "{Fluid:plasma.sixphasedcopper}" },
	},
}