return {
  robotarmluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22374,
        Amount = 4,
        Fluid = false,
        Label = "Long HSS-S Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31374,
        Amount = 1,
        Fluid = false,
        Label = "HSS-S Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20374,
        Amount = 3,
        Fluid = false,
        Label = "Small HSS-S Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32606,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (LuV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32645,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (LuV)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32096,
        Amount = 2,
        Fluid = false,
        Label = "Crystalprocessor Assembly",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32089,
        Amount = 4,
        Fluid = false,
        Label = "Crystalprocessor",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32085,
        Amount = 8,
        Fluid = false,
        Label = "Quantumprocessor",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1766,
        Amount = 6,
        Fluid = false,
        Label = "1x Yttrium Barium Cuprate Cable",
      },
      [10] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [11] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 250,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Robot Arm (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32655,
  },
  electricpumpluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32606,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (LuV)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5181,
        Amount = 2,
        Fluid = false,
        Label = "Small Niobium-Titanium Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17374,
        Amount = 2,
        Fluid = false,
        Label = "HSS-S Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27374,
        Amount = 8,
        Fluid = false,
        Label = "HSS-S Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 4,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21374,
        Amount = 2,
        Fluid = false,
        Label = "HSS-S Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1766,
        Amount = 2,
        Fluid = false,
        Label = "1x Yttrium Barium Cuprate Cable",
      },
      [8] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 144,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [9] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 250,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Pump (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32615,
  },
  electricmotorluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 23399,
        Amount = 1,
        Fluid = false,
        Label = "Magnetic Samarium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22374,
        Amount = 2,
        Fluid = false,
        Label = "Long HSS-S Rod",
      },
      [3] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [4] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1766,
        Amount = 2,
        Fluid = false,
        Label = "1x Yttrium Barium Cuprate Cable",
      },
      [6] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 144,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [7] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 250,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Motor (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32606,
  },
  fieldgeneratorluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 374,
        Amount = 1,
        Fluid = false,
        Label = "HSS-S Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17374,
        Amount = 6,
        Fluid = false,
        Label = "HSS-S Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32725,
        Amount = 2,
        Fluid = false,
        Label = "Quantum Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32685,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (LuV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32090,
        Amount = 4,
        Fluid = false,
        Label = "Ultimate Crystalcomputer",
      },
      [6] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [7] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [8] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [9] = {
        Name = "bartworks:gt.bwMetaGeneratedwireFine",
        ID = 90,
        Amount = 64,
        Fluid = false,
        Label = "Fine Ruridit Wire",
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1766,
        Amount = 8,
        Fluid = false,
        Label = "1x Yttrium Barium Cuprate Cable",
      },
      [11] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
    },
    Label = "Field Generator (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32675,
  },
  conveyormoduleluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32606,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (LuV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17374,
        Amount = 2,
        Fluid = false,
        Label = "HSS-S Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28374,
        Amount = 4,
        Fluid = false,
        Label = "HSS-S Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25374,
        Amount = 32,
        Fluid = false,
        Label = "HSS-S Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1766,
        Amount = 2,
        Fluid = false,
        Label = "1x Yttrium Barium Cuprate Cable",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 10,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [7] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 144,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [8] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 250,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Conveyor Module (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32635,
  },
  electricpistonluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32606,
        Label = "Electric Motor (LuV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17374,
        Label = "HSS-S Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 28374,
        Label = "HSS-S Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 25374,
        Label = "HSS-S Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 23374,
        Label = "HSS-S Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 1,
        ID = 31374,
        Label = "HSS-S Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 20374,
        Label = "Small HSS-S Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 1766,
        Label = "1x Yttrium Barium Cuprate Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:molten.indalloy140}",
        Amount = 144,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        Amount = 250,
        ID = 0,
        Label = "drop of Lubricant",
        Fluid = true,
      },
    },
    Label = "Electric Piston (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32645,
  },
  sensorluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 374,
        Label = "HSS-S Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32606,
        Label = "Electric Motor (LuV)",
        Fluid = false,
      },
      [3] = {
        Name = "bartworks:gt.bwMetaGeneratedplate",
        Amount = 8,
        ID = 90,
        Label = "Ruridit Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32725,
        Label = "Quantum Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32096,
        Label = "Crystalprocessor Assembly",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1766,
        Label = "1x Yttrium Barium Cuprate Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:molten.indalloy140}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Label = "Sensor (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32695,
  },
  emitterluv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 374,
        Label = "HSS-S Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32606,
        Label = "Electric Motor (LuV)",
        Fluid = false,
      },
      [3] = {
        Name = "bartworks:gt.bwMetaGeneratedstick",
        Amount = 8,
        ID = 90,
        Label = "Ruridit Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32725,
        Label = "Quantum Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32096,
        Label = "Crystalprocessor Assembly",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29037,
        Label = "Gallium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1766,
        Label = "1x Yttrium Barium Cuprate Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:molten.indalloy140}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Label = "Emitter (LuV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32685,
  },
}