return {
  electricpumpuev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32595,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UEV)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5223,
        Amount = 2,
        Fluid = false,
        Label = "Large Nether Star Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17397,
        Amount = 4,
        Fluid = false,
        Label = "Infinity Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27397,
        Amount = 16,
        Fluid = false,
        Label = "Infinity Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 64,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21397,
        Amount = 4,
        Fluid = false,
        Label = "Infinity Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11338,
        Amount = 2,
        Fluid = false,
        Label = "4x Draconium Cable",
      },
      [8] = {
        Name = "{Fluid:molten.quantium}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Quantium",
      },
      [9] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Pump (UEV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32619,
  },
  conveyormoduleuev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32595,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UEV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17397,
        Amount = 2,
        Fluid = false,
        Label = "Infinity Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28397,
        Amount = 8,
        Fluid = false,
        Label = "Infinity Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25397,
        Amount = 64,
        Fluid = false,
        Label = "Infinity Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11338,
        Amount = 2,
        Fluid = false,
        Label = "4x Draconium Cable",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 64,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 16,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [8] = {
        Name = "{Fluid:molten.quantium}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Quantium",
      },
      [9] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Conveyor Module (UEV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32639,
  },
  fieldgeneratoruev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 397,
        Amount = 1,
        Fluid = false,
        Label = "Infinity Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17397,
        Amount = 6,
        Fluid = false,
        Label = "Infinity Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32726,
        Amount = 8,
        Fluid = false,
        Label = "Gravi Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32689,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (UEV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32157,
        Amount = 4,
        Fluid = false,
        Label = "Optical Mainframe",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [13] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19329,
        Amount = 64,
        Fluid = false,
        Label = "Fine Tritanium Wire",
      },
      [14] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11338,
        Amount = 8,
        Fluid = false,
        Label = "4x Draconium Cable",
      },
      [15] = {
        Name = "{Fluid:molten.quantium}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Quantium",
      },
      [16] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
    },
    Label = "Field Generator (UEV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32679,
  },
  electricmotoruev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22112,
        Amount = 8,
        Fluid = false,
        Label = "Long Attuned Tengam Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22397,
        Amount = 16,
        Fluid = false,
        Label = "Long Infinity Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28397,
        Amount = 8,
        Fluid = false,
        Label = "Infinity Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25397,
        Amount = 32,
        Fluid = false,
        Label = "Infinity Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19982,
        Amount = 64,
        Fluid = false,
        Label = "Fine Cosmic Neutronium Wire",
      },
      [13] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11338,
        Amount = 2,
        Fluid = false,
        Label = "4x Draconium Cable",
      },
      [14] = {
        Name = "{Fluid:molten.quantium}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Quantium",
      },
      [15] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [16] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Motor (UEV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32595,
  },
  robotarmuev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22397,
        Amount = 8,
        Fluid = false,
        Label = "Long Infinity Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31397,
        Amount = 2,
        Fluid = false,
        Label = "Infinity Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20397,
        Amount = 6,
        Fluid = false,
        Label = "Small Infinity Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32595,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UEV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32649,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (UEV)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32120,
        Amount = 2,
        Fluid = false,
        Label = "Bio Mainframe",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32099,
        Amount = 4,
        Fluid = false,
        Label = "Bioware Supercomputer",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32094,
        Amount = 8,
        Fluid = false,
        Label = "Wetware Supercomputer",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11338,
        Amount = 6,
        Fluid = false,
        Label = "4x Draconium Cable",
      },
      [10] = {
        Name = "{Fluid:molten.quantium}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Quantium",
      },
      [11] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [12] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Robot Arm (UEV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32659,
  },
  emitteruev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 397,
        Label = "Infinity Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32595,
        Label = "Electric Motor (UEV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 23397,
        Label = "Infinity Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32120,
        Label = "Bio Mainframe",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11338,
        Label = "4x Draconium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.quantium}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Quantium",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (UEV)",
    ID = 32689,
  },
  sensoruev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 397,
        Label = "Infinity Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32595,
        Label = "Electric Motor (UEV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17397,
        Label = "Infinity Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32120,
        Label = "Bio Mainframe",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29394,
        Label = "Infinity Catalyst Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11338,
        Label = "4x Draconium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.quantium}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Quantium",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Sensor (UEV)",
    ID = 32699,
  },
  electricpistonuev = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32595,
        Label = "Electric Motor (UEV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17397,
        Label = "Infinity Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28397,
        Label = "Infinity Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 25397,
        Label = "Infinity Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23397,
        Label = "Infinity Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31397,
        Label = "Infinity Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 20397,
        Label = "Small Infinity Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 11338,
        Label = "4x Draconium Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:molten.quantium}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Quantium",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:lubricant}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Lubricant",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Piston (UEV)",
    ID = 32649,
  },
}