return {
  robotarmuhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22982,
        Amount = 8,
        Fluid = false,
        Label = "Long Cosmic Neutronium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31982,
        Amount = 2,
        Fluid = false,
        Label = "Cosmic Neutronium Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20982,
        Amount = 6,
        Fluid = false,
        Label = "Small Cosmic Neutronium Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32596,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UHV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32648,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (UHV)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32099,
        Amount = 2,
        Fluid = false,
        Label = "Bioware Supercomputer",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32094,
        Amount = 4,
        Fluid = false,
        Label = "Wetware Supercomputer",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32090,
        Amount = 8,
        Fluid = false,
        Label = "Ultimate Crystalcomputer",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11318,
        Amount = 6,
        Fluid = false,
        Label = "4x Bedrockium Cable",
      },
      [10] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [11] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [12] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Robot Arm (UHV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32658,
  },
  fieldgeneratoruhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 982,
        Amount = 1,
        Fluid = false,
        Label = "Cosmic Neutronium Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17982,
        Amount = 6,
        Fluid = false,
        Label = "Cosmic Neutronium Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32726,
        Amount = 4,
        Fluid = false,
        Label = "Gravi Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32688,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (UHV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32120,
        Amount = 4,
        Fluid = false,
        Label = "Bio Mainframe",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [13] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [14] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11318,
        Amount = 8,
        Fluid = false,
        Label = "4x Bedrockium Cable",
      },
      [15] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [16] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
    },
    Label = "Field Generator (UHV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32678,
  },
  conveyormoduleuhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32596,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UHV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17982,
        Amount = 2,
        Fluid = false,
        Label = "Cosmic Neutronium Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28982,
        Amount = 8,
        Fluid = false,
        Label = "Cosmic Neutronium Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25982,
        Amount = 64,
        Fluid = false,
        Label = "Cosmic Neutronium Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11318,
        Amount = 2,
        Fluid = false,
        Label = "4x Bedrockium Cable",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 40,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [7] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [8] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [9] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Conveyor Module (UHV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32638,
  },
  electricmotoruhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22399,
        Amount = 4,
        Fluid = false,
        Label = "Long Magnetic Samarium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22982,
        Amount = 8,
        Fluid = false,
        Label = "Long Cosmic Neutronium Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28982,
        Amount = 8,
        Fluid = false,
        Label = "Cosmic Neutronium Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25982,
        Amount = 32,
        Fluid = false,
        Label = "Cosmic Neutronium Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19129,
        Amount = 64,
        Fluid = false,
        Label = "Fine Neutronium Wire",
      },
      [13] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11318,
        Amount = 2,
        Fluid = false,
        Label = "4x Bedrockium Cable",
      },
      [14] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [15] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [16] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Motor (UHV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32596,
  },
  electricpumpuhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32596,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UHV)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5213,
        Amount = 2,
        Fluid = false,
        Label = "Large Neutronium Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17982,
        Amount = 4,
        Fluid = false,
        Label = "Cosmic Neutronium Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27982,
        Amount = 16,
        Fluid = false,
        Label = "Cosmic Neutronium Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 32,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21982,
        Amount = 4,
        Fluid = false,
        Label = "Cosmic Neutronium Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11318,
        Amount = 2,
        Fluid = false,
        Label = "4x Bedrockium Cable",
      },
      [8] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [9] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Pump (UHV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32618,
  },
  emitteruhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 982,
        Label = "Cosmic Neutronium Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32596,
        Label = "Electric Motor (UHV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23982,
        Label = "Cosmic Neutronium Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32099,
        Label = "Bioware Supercomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11318,
        Label = "4x Bedrockium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (UHV)",
    ID = 32688,
  },
  electricpistonuhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32596,
        Label = "Electric Motor (UHV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17982,
        Label = "Cosmic Neutronium Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28982,
        Label = "Cosmic Neutronium Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 25982,
        Label = "Cosmic Neutronium Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23982,
        Label = "Cosmic Neutronium Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31982,
        Label = "Cosmic Neutronium Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 20982,
        Label = "Small Cosmic Neutronium Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 11318,
        Label = "4x Bedrockium Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:plasma.lubricant}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Lubricant",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Piston (UHV)",
    ID = 32648,
  },
  sensoruhv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 982,
        Label = "Cosmic Neutronium Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32596,
        Label = "Electric Motor (UHV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17982,
        Label = "Cosmic Neutronium Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32099,
        Label = "Bioware Supercomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29320,
        Label = "Fluxed Electrum Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11318,
        Label = "4x Bedrockium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Sensor (UHV)",
    ID = 32698,
  },
}