return {
  electricpistonuiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32017,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UIV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17581,
        Amount = 6,
        Fluid = false,
        Label = "Transcendent Metal Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28581,
        Amount = 8,
        Fluid = false,
        Label = "Transcendent Metal Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25581,
        Amount = 64,
        Fluid = false,
        Label = "Transcendent Metal Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 23581,
        Amount = 8,
        Fluid = false,
        Label = "Transcendent Metal Rod",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31581,
        Amount = 2,
        Fluid = false,
        Label = "Transcendent Metal Gear",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20581,
        Amount = 4,
        Fluid = false,
        Label = "Small Transcendent Metal Gear",
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11358,
        Amount = 4,
        Fluid = false,
        Label = "4x Nether Star Cable",
      },
      [9] = {
        Name = "{Fluid:molten.celestialtungsten}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Celestial Tungsten",
      },
      [10] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [11] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Electric Piston (UIV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32021,
  },
  robotarmuiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22581,
        Amount = 8,
        Fluid = false,
        Label = "Long Transcendent Metal Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31581,
        Amount = 2,
        Fluid = false,
        Label = "Transcendent Metal Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20581,
        Amount = 6,
        Fluid = false,
        Label = "Small Transcendent Metal Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32017,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UIV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32021,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (UIV)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32157,
        Amount = 2,
        Fluid = false,
        Label = "Optical Mainframe",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32120,
        Amount = 4,
        Fluid = false,
        Label = "Bio Mainframe",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32099,
        Amount = 8,
        Fluid = false,
        Label = "Bioware Supercomputer",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11358,
        Amount = 6,
        Fluid = false,
        Label = "4x Nether Star Cable",
      },
      [10] = {
        Name = "{Fluid:molten.celestialtungsten}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Celestial Tungsten",
      },
      [11] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [12] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Robot Arm (UIV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32033,
  },
  emitteruiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 581,
        Amount = 1,
        Fluid = false,
        Label = "Transcendent Metal Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32017,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UIV)",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 23581,
        Amount = 16,
        Fluid = false,
        Label = "Transcendent Metal Rod",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32726,
        Amount = 32,
        Fluid = false,
        Label = "Gravi Star",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32157,
        Amount = 4,
        Fluid = false,
        Label = "Optical Mainframe",
      },
      [6] = {
        Name = "miscutils:itemFoilArceusAlloy2B",
        ID = 0,
        Amount = 64,
        Fluid = false,
        Label = "Arceus Alloy 2B Foil",
      },
      [7] = {
        Name = "miscutils:itemFoilLafiumCompound",
        ID = 0,
        Amount = 64,
        Fluid = false,
        Label = "Lafium Compound Foil",
      },
      [8] = {
        Name = "miscutils:itemFoilCinobiteA243",
        ID = 0,
        Amount = 64,
        Fluid = false,
        Label = "Cinobite A243 Foil",
      },
      [9] = {
        Name = "miscutils:itemFoilPikyonium64B",
        ID = 0,
        Amount = 64,
        Fluid = false,
        Label = "Pikyonium 64B Foil",
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11358,
        Amount = 7,
        Fluid = false,
        Label = "4x Nether Star Cable",
      },
      [11] = {
        Name = "{Fluid:molten.celestialtungsten}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Celestial Tungsten",
      },
      [12] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
    },
    Label = "Emitter (UIV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32037,
  },
  electricmotoruiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22112,
        Amount = 16,
        Fluid = false,
        Label = "Long Attuned Tengam Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22581,
        Amount = 16,
        Fluid = false,
        Label = "Long Transcendent Metal Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28581,
        Amount = 8,
        Fluid = false,
        Label = "Transcendent Metal Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25581,
        Amount = 32,
        Fluid = false,
        Label = "Transcendent Metal Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19154,
        Amount = 64,
        Fluid = false,
        Label = "Fine Proto-Halkonite Steel Wire",
      },
      [13] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11358,
        Amount = 2,
        Fluid = false,
        Label = "4x Nether Star Cable",
      },
      [14] = {
        Name = "{Fluid:molten.celestialtungsten}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Celestial Tungsten",
      },
      [15] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [16] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Electric Motor (UIV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32017,
  },
  electricpumpuiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32017,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UIV)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5243,
        Amount = 2,
        Fluid = false,
        Label = "Large Awakened Draconium Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17581,
        Amount = 4,
        Fluid = false,
        Label = "Transcendent Metal Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27581,
        Amount = 16,
        Fluid = false,
        Label = "Transcendent Metal Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 64,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21581,
        Amount = 4,
        Fluid = false,
        Label = "Transcendent Metal Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 11358,
        Amount = 2,
        Fluid = false,
        Label = "4x Nether Star Cable",
      },
      [8] = {
        Name = "{Fluid:molten.celestialtungsten}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Celestial Tungsten",
      },
      [9] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 2592,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
      [10] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 4000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Electric Pump (UIV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32025,
  },
  conveyormoduleuiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32017,
        Label = "Electric Motor (UIV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 17581,
        Label = "Transcendent Metal Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28581,
        Label = "Transcendent Metal Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 25581,
        Label = "Transcendent Metal Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 11358,
        Label = "4x Nether Star Cable",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 17471,
        Label = "Silicone Rubber Sheet",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 17471,
        Label = "Silicone Rubber Sheet",
        Fluid = false,
      },
      [8] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [9] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Conveyor Module (UIV)",
    ID = 32029,
  },
  sensoruiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 581,
        Label = "Transcendent Metal Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32017,
        Label = "Electric Motor (UIV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17581,
        Label = "Transcendent Metal Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32157,
        Label = "Optical Mainframe",
        Fluid = false,
      },
      [6] = {
        Name = "miscutils:itemFoilArceusAlloy2B",
        Amount = 64,
        ID = 0,
        Label = "Arceus Alloy 2B Foil",
        Fluid = false,
      },
      [7] = {
        Name = "miscutils:itemFoilLafiumCompound",
        Amount = 64,
        ID = 0,
        Label = "Lafium Compound Foil",
        Fluid = false,
      },
      [8] = {
        Name = "miscutils:itemFoilCinobiteA243",
        Amount = 64,
        ID = 0,
        Label = "Cinobite A243 Foil",
        Fluid = false,
      },
      [9] = {
        Name = "miscutils:itemFoilPikyonium64B",
        Amount = 64,
        ID = 0,
        Label = "Pikyonium 64B Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11358,
        Label = "4x Nether Star Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Sensor (UIV)",
    ID = 32041,
  },
  electricpumpuiv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32017,
        Label = "Electric Motor (UIV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 5243,
        Label = "Large Awakened Draconium Fluid Pipe",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 17581,
        Label = "Transcendent Metal Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 27581,
        Label = "Transcendent Metal Screw",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 28471,
        Label = "Silicone Rubber Ring",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 21581,
        Label = "Transcendent Metal Rotor",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 11358,
        Label = "4x Nether Star Cable",
        Fluid = false,
      },
      [8] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [9] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Pump (UIV)",
    ID = 32025,
  },
}