return {
  electricpumpumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 5253,
        Label = "Large Infinity Fluid Pipe",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 17588,
        Label = "SpaceTime Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 27588,
        Label = "SpaceTime Screw",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 28471,
        Label = "Silicone Rubber Ring",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 21588,
        Label = "SpaceTime Rotor",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [8] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [9] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Pump (UMV)",
    ID = 32026,
  },
  electricpistonumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17588,
        Label = "SpaceTime Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28588,
        Label = "SpaceTime Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 25588,
        Label = "SpaceTime Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23588,
        Label = "SpaceTime Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31588,
        Label = "SpaceTime Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 20588,
        Label = "Small SpaceTime Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Piston (UMV)",
    ID = 32022,
  },
  fieldgeneratorumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 588,
        Label = "SpaceTime Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17588,
        Label = "SpaceTime Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 32038,
        Label = "Emitter (UMV)",
        Fluid = false,
      },
      [5] = {
        Name = "dreamcraft:item.QuantumCircuit",
        Amount = 4,
        ID = 0,
        Label = "Quantum Circuit",
        Fluid = false,
      },
      [6] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [7] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [8] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [9] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [10] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [11] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [12] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [13] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [14] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 8,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [15] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [16] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [17] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Field Generator (UMV)",
    ID = 32046,
  },
  electricmotorumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 32,
        ID = 22112,
        Label = "Long Attuned Tengam Rod",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 16,
        ID = 22588,
        Label = "Long SpaceTime Rod",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28588,
        Label = "SpaceTime Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 25588,
        Label = "SpaceTime Round",
        Fluid = false,
      },
      [5] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [6] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [7] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [8] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [9] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [10] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [11] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [12] = {
        Name = "miscutils:itemFineWireHypogen",
        Amount = 64,
        ID = 0,
        Label = "Fine Hypogen Wire",
        Fluid = false,
      },
      [13] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [14] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [15] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [16] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [17] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Motor (UMV)",
    ID = 32018,
  },
  robotarmumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 8,
        ID = 22588,
        Label = "Long SpaceTime Rod",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31588,
        Label = "SpaceTime Gear",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 6,
        ID = 20588,
        Label = "Small SpaceTime Gear",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32022,
        Label = "Electric Piston (UMV)",
        Fluid = false,
      },
      [6] = {
        Name = "dreamcraft:item.PikoCircuit",
        Amount = 2,
        ID = 0,
        Label = "Pico Circuit",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32157,
        Label = "Optical Mainframe",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 8,
        ID = 32120,
        Label = "Bio Mainframe",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 6,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [13] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Robot Arm (UMV)",
    ID = 32034,
  },
  conveyormoduleumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 17588,
        Label = "SpaceTime Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 28588,
        Label = "SpaceTime Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 25588,
        Label = "SpaceTime Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 17471,
        Label = "Silicone Rubber Sheet",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 17471,
        Label = "Silicone Rubber Sheet",
        Fluid = false,
      },
      [8] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [9] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 4000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Conveyor Module (UMV)",
    ID = 32030,
  },
  sensorumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 588,
        Label = "SpaceTime Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17588,
        Label = "SpaceTime Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "dreamcraft:item.PikoCircuit",
        Amount = 4,
        ID = 0,
        Label = "Pico Circuit",
        Fluid = false,
      },
      [6] = {
        Name = "miscutils:itemFoilCelestialTungsten",
        Amount = 64,
        ID = 0,
        Label = "Celestial Tungsten Foil",
        Fluid = false,
      },
      [7] = {
        Name = "miscutils:itemFoilQuantum",
        Amount = 64,
        ID = 0,
        Label = "Quantum Foil",
        Fluid = false,
      },
      [8] = {
        Name = "miscutils:itemFoilAstralTitanium",
        Amount = 64,
        ID = 0,
        Label = "Astral Titanium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "miscutils:itemFoilTitansteel",
        Amount = 64,
        ID = 0,
        Label = "Titansteel Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [13] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Sensor (UMV)",
    ID = 32042,
  },
  emitterumv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 588,
        Label = "SpaceTime Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32018,
        Label = "Electric Motor (UMV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 23588,
        Label = "SpaceTime Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "dreamcraft:item.PikoCircuit",
        Amount = 4,
        ID = 0,
        Label = "Pico Circuit",
        Fluid = false,
      },
      [6] = {
        Name = "miscutils:itemFoilCelestialTungsten",
        Amount = 64,
        ID = 0,
        Label = "Celestial Tungsten Foil",
        Fluid = false,
      },
      [7] = {
        Name = "miscutils:itemFoilQuantum",
        Amount = 64,
        ID = 0,
        Label = "Quantum Foil",
        Fluid = false,
      },
      [8] = {
        Name = "miscutils:itemFoilAstralTitanium",
        Amount = 64,
        ID = 0,
        Label = "Astral Titanium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "miscutils:itemFoilTitansteel",
        Amount = 64,
        ID = 0,
        Label = "Titansteel Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 11378,
        Label = "4x Quantium Cable",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.hypogen}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Hypogen",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.celestialtungsten}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Celestial Tungsten",
        Fluid = true,
      },
      [13] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 2592,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (UMV)",
    ID = 32038,
  },
}