return {
  electricmotoruv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22399,
        Amount = 2,
        Fluid = false,
        Label = "Long Magnetic Samarium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22129,
        Amount = 4,
        Fluid = false,
        Label = "Long Neutronium Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28129,
        Amount = 4,
        Fluid = false,
        Label = "Neutronium Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25129,
        Amount = 16,
        Fluid = false,
        Label = "Neutronium Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [11] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1808,
        Amount = 2,
        Fluid = false,
        Label = "4x Naquadah Alloy Cable",
      },
      [12] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [13] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [14] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 2000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Motor (UV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32608,
  },
  fieldgeneratoruv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 129,
        Amount = 1,
        Fluid = false,
        Label = "Neutronium Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17129,
        Amount = 6,
        Fluid = false,
        Label = "Neutronium Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32726,
        Amount = 2,
        Fluid = false,
        Label = "Gravi Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32687,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (UV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32099,
        Amount = 4,
        Fluid = false,
        Label = "Bioware Supercomputer",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19103,
        Amount = 64,
        Fluid = false,
        Label = "Fine Americium Wire",
      },
      [12] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1808,
        Amount = 8,
        Fluid = false,
        Label = "4x Naquadah Alloy Cable",
      },
      [13] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [14] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2304,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
    },
    Label = "Field Generator (UV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32677,
  },
  electricpumpuv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32608,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UV)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5203,
        Amount = 2,
        Fluid = false,
        Label = "Large Naquadah Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17129,
        Amount = 2,
        Fluid = false,
        Label = "Neutronium Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27129,
        Amount = 8,
        Fluid = false,
        Label = "Neutronium Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 16,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21129,
        Amount = 2,
        Fluid = false,
        Label = "Neutronium Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1808,
        Amount = 2,
        Fluid = false,
        Label = "4x Naquadah Alloy Cable",
      },
      [8] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [9] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 2000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Pump (UV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32617,
  },
  robotarmuv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22129,
        Amount = 4,
        Fluid = false,
        Label = "Long Neutronium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31129,
        Amount = 1,
        Fluid = false,
        Label = "Neutronium Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20129,
        Amount = 3,
        Fluid = false,
        Label = "Small Neutronium Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32608,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UV)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32647,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (UV)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32094,
        Amount = 2,
        Fluid = false,
        Label = "Wetware Supercomputer",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32090,
        Amount = 4,
        Fluid = false,
        Label = "Ultimate Crystalcomputer",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32096,
        Amount = 8,
        Fluid = false,
        Label = "Crystalprocessor Assembly",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1808,
        Amount = 6,
        Fluid = false,
        Label = "4x Naquadah Alloy Cable",
      },
      [10] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [11] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 2304,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [12] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 2000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Robot Arm (UV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32657,
  },
  conveyormoduleuv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32608,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17129,
        Amount = 2,
        Fluid = false,
        Label = "Neutronium Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28129,
        Amount = 4,
        Fluid = false,
        Label = "Neutronium Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25129,
        Amount = 32,
        Fluid = false,
        Label = "Neutronium Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1808,
        Amount = 2,
        Fluid = false,
        Label = "4x Naquadah Alloy Cable",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 40,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [7] = {
        Name = "{Fluid:molten.naquadria}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Naquadria",
      },
      [8] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 1296,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [9] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 2000,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Conveyor Module (UV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32637,
  },
  sensoruv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 129,
        Label = "Neutronium Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32608,
        Label = "Electric Motor (UV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17129,
        Label = "Neutronium Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32094,
        Label = "Wetware Supercomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1808,
        Label = "4x Naquadah Alloy Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 1296,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 2304,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    ID = 32697,
  },
  electricpistonuv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32608,
        Label = "Electric Motor (UV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17129,
        Label = "Neutronium Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 28129,
        Label = "Neutronium Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 25129,
        Label = "Neutronium Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 23129,
        Label = "Neutronium Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 1,
        ID = 31129,
        Label = "Neutronium Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 20129,
        Label = "Small Neutronium Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 1808,
        Label = "4x Naquadah Alloy Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 1296,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 1296,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:plasma.lubricant}",
        Amount = 2000,
        ID = 0,
        Label = "drop of Lubricant",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Piston (UV)",
    ID = 32647,
  },
  emitteruv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 129,
        Label = "Neutronium Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32608,
        Label = "Electric Motor (UV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23129,
        Label = "Neutronium Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 32726,
        Label = "Gravi Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32094,
        Label = "Wetware Supercomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29327,
        Label = "Naquadria Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1808,
        Label = "4x Naquadah Alloy Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.naquadria}",
        Amount = 1296,
        ID = 0,
        Label = "drop of Molten Naquadria",
        Fluid = true,
      },
      [11] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 2304,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (UV)",
    ID = 32687,
  },
}