return {
  electricpistonuxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32019,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UXV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17583,
        Amount = 6,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28583,
        Amount = 8,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25583,
        Amount = 64,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 23583,
        Amount = 8,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Rod",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31583,
        Amount = 2,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Gear",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31143,
        Amount = 2,
        Fluid = false,
        Label = "Magmatter Gear",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20583,
        Amount = 4,
        Fluid = false,
        Label = "Small Magnetohydrodynamically Constrained Star Matter Gear",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20143,
        Amount = 4,
        Fluid = false,
        Label = "Small Magmatter Gear",
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        ID = 2608,
        Amount = 8,
        Fluid = false,
        Label = "4x SpaceTime Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 4129,
        Amount = 4,
        Fluid = false,
        Label = "Neutronium Nanites",
      },
      [12] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
      },
      [13] = {
        Name = "{Fluid:molten.spacetime}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten SpaceTime",
      },
      [14] = {
        Name = "{Fluid:molten.universium}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Universium",
      },
      [15] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 8000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Electric Piston (UXV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32023,
  },
  conveyormoduleuxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32019,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (UXV)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17583,
        Amount = 2,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28583,
        Amount = 8,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25583,
        Amount = 64,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 2608,
        Amount = 4,
        Fluid = false,
        Label = "4x SpaceTime Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17765,
        Amount = 64,
        Fluid = false,
        Label = "Kevlar Plate",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17765,
        Amount = 16,
        Fluid = false,
        Label = "Kevlar Plate",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17979,
        Amount = 64,
        Fluid = false,
        Label = "Radox Polymer Plate",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17979,
        Amount = 16,
        Fluid = false,
        Label = "Radox Polymer Plate",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 4129,
        Amount = 4,
        Fluid = false,
        Label = "Neutronium Nanites",
      },
      [11] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
      },
      [12] = {
        Name = "{Fluid:molten.spacetime}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten SpaceTime",
      },
      [13] = {
        Name = "{Fluid:molten.universium}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Universium",
      },
      [14] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 8000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Conveyor Module (UXV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32031,
  },
  sensoruxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 583,
        Amount = 1,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32019,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (UXV)",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17583,
        Amount = 8,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32230,
        Amount = 16,
        Fluid = false,
        Label = "Nuclear Star",
      },
      [5] = {
        Name = "dreamcraft:item.QuantumCircuit",
        ID = 0,
        Amount = 4,
        Fluid = false,
        Label = "Quantum Circuit",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 29583,
        Amount = 64,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Foil",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 29143,
        Amount = 64,
        Fluid = false,
        Label = "Magmatter Foil",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 29588,
        Amount = 64,
        Fluid = false,
        Label = "SpaceTime Foil",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 29139,
        Amount = 64,
        Fluid = false,
        Label = "Universium Foil",
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        ID = 2608,
        Amount = 14,
        Fluid = false,
        Label = "4x SpaceTime Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 4129,
        Amount = 8,
        Fluid = false,
        Label = "Neutronium Nanites",
      },
      [12] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
      },
      [13] = {
        Name = "{Fluid:molten.spacetime}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten SpaceTime",
      },
      [14] = {
        Name = "{Fluid:molten.universium}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Universium",
      },
      [15] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 14400,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
    },
    Label = "Sensor (UXV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32043,
  },
  fieldgeneratoruxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 583,
        Amount = 1,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17583,
        Amount = 6,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32230,
        Amount = 64,
        Fluid = false,
        Label = "Nuclear Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32039,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (UXV)",
      },
      [5] = {
        Name = "dreamcraft:item.QuantumCircuit",
        ID = 0,
        Amount = 8,
        Fluid = false,
        Label = "Quantum Circuit",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19134,
        Amount = 64,
        Fluid = false,
        Label = "Fine Superconductor Base UMV Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19134,
        Amount = 64,
        Fluid = false,
        Label = "Fine Superconductor Base UMV Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19583,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magnetohydrodynamically Constrained Star Matter Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19583,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magnetohydrodynamically Constrained Star Matter Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19139,
        Amount = 64,
        Fluid = false,
        Label = "Fine Universium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19139,
        Amount = 64,
        Fluid = false,
        Label = "Fine Universium Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19143,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magmatter Wire",
      },
      [13] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19143,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magmatter Wire",
      },
      [14] = {
        Name = "gregtech:gt.blockmachines",
        ID = 2608,
        Amount = 16,
        Fluid = false,
        Label = "4x SpaceTime Wire",
      },
      [15] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 4129,
        Amount = 12,
        Fluid = false,
        Label = "Neutronium Nanites",
      },
      [16] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
      },
      [17] = {
        Name = "{Fluid:molten.spacetime}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten SpaceTime",
      },
      [18] = {
        Name = "{Fluid:molten.universium}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Universium",
      },
      [19] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        ID = 0,
        Amount = 14400,
        Fluid = true,
        Label = "drop of Mutated Living Solder",
      },
    },
    Label = "Field Generator (UXV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32047,
  },
  electricmotoruxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32417,
        Amount = 1,
        Fluid = false,
        Label = "Energised Tesseract",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22583,
        Amount = 16,
        Fluid = false,
        Label = "Long Magnetohydrodynamically Constrained Star Matter Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28583,
        Amount = 8,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25583,
        Amount = 32,
        Fluid = false,
        Label = "Magnetohydrodynamically Constrained Star Matter Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19134,
        Amount = 64,
        Fluid = false,
        Label = "Fine Superconductor Base UMV Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19134,
        Amount = 64,
        Fluid = false,
        Label = "Fine Superconductor Base UMV Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19583,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magnetohydrodynamically Constrained Star Matter Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19583,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magnetohydrodynamically Constrained Star Matter Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19139,
        Amount = 64,
        Fluid = false,
        Label = "Fine Universium Wire",
      },
      [10] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19139,
        Amount = 64,
        Fluid = false,
        Label = "Fine Universium Wire",
      },
      [11] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19143,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magmatter Wire",
      },
      [12] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19143,
        Amount = 64,
        Fluid = false,
        Label = "Fine Magmatter Wire",
      },
      [13] = {
        Name = "gregtech:gt.blockmachines",
        ID = 2608,
        Amount = 4,
        Fluid = false,
        Label = "4x SpaceTime Wire",
      },
      [14] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 4129,
        Amount = 4,
        Fluid = false,
        Label = "Neutronium Nanites",
      },
      [15] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
      },
      [16] = {
        Name = "{Fluid:molten.spacetime}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten SpaceTime",
      },
      [17] = {
        Name = "{Fluid:molten.universium}",
        ID = 0,
        Amount = 576,
        Fluid = true,
        Label = "drop of Molten Universium",
      },
      [18] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        ID = 0,
        Amount = 8000,
        Fluid = true,
        Label = "drop of Dimensionally Shifted Superfluid",
      },
    },
    Label = "Electric Motor (UXV)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32019,
  },
  robotarmuxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 8,
        ID = 22583,
        Label = "Long Magnetohydrodynamically Constrained Star Matter Rod",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31583,
        Label = "Magnetohydrodynamically Constrained Star Matter Gear",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 31143,
        Label = "Magmatter Gear",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 6,
        ID = 20583,
        Label = "Small Magnetohydrodynamically Constrained Star Matter Gear",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 6,
        ID = 20143,
        Label = "Small Magmatter Gear",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32019,
        Label = "Electric Motor (UXV)",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32023,
        Label = "Electric Piston (UXV)",
        Fluid = false,
      },
      [8] = {
        Name = "dreamcraft:item.QuantumCircuit",
        Amount = 2,
        ID = 0,
        Label = "Quantum Circuit",
        Fluid = false,
      },
      [9] = {
        Name = "dreamcraft:item.PikoCircuit",
        Amount = 4,
        ID = 0,
        Label = "Pico Circuit",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 8,
        ID = 32157,
        Label = "Optical Mainframe",
        Fluid = false,
      },
      [11] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 12,
        ID = 2608,
        Label = "4x SpaceTime Wire",
        Fluid = false,
      },
      [12] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 8,
        ID = 4129,
        Label = "Neutronium Nanites",
        Fluid = false,
      },
      [13] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
        Fluid = true,
      },
      [14] = {
        Name = "{Fluid:molten.spacetime}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten SpaceTime",
        Fluid = true,
      },
      [15] = {
        Name = "{Fluid:molten.universium}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Universium",
        Fluid = true,
      },
      [16] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 8000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Robot Arm (UXV)",
    ID = 32035,
  },
  electricpumpuxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32019,
        Label = "Electric Motor (UXV)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 2,
        ID = 5303,
        Label = "Large SpaceTime Fluid Pipe",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 17583,
        Label = "Magnetohydrodynamically Constrained Star Matter Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 27583,
        Label = "Magnetohydrodynamically Constrained Star Matter Screw",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 28765,
        Label = "Kevlar Ring",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 28979,
        Label = "Radox Polymer Ring",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 21583,
        Label = "Magnetohydrodynamically Constrained Star Matter Rotor",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 4,
        ID = 21143,
        Label = "Magmatter Rotor",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 2608,
        Label = "4x SpaceTime Wire",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 4129,
        Label = "Neutronium Nanites",
        Fluid = false,
      },
      [11] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
        Fluid = true,
      },
      [12] = {
        Name = "{Fluid:molten.spacetime}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten SpaceTime",
        Fluid = true,
      },
      [13] = {
        Name = "{Fluid:molten.universium}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Universium",
        Fluid = true,
      },
      [14] = {
        Name = "{Fluid:dimensionallyshiftedsuperfluid}",
        Amount = 8000,
        ID = 0,
        Label = "drop of Dimensionally Shifted Superfluid",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Pump (UXV)",
    ID = 32027,
  },
  emitteruxv = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 583,
        Label = "Magnetohydrodynamically Constrained Star Matter Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32019,
        Label = "Electric Motor (UXV)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 16,
        ID = 23583,
        Label = "Magnetohydrodynamically Constrained Star Matter Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 16,
        ID = 32230,
        Label = "Nuclear Star",
        Fluid = false,
      },
      [5] = {
        Name = "dreamcraft:item.QuantumCircuit",
        Amount = 4,
        ID = 0,
        Label = "Quantum Circuit",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29583,
        Label = "Magnetohydrodynamically Constrained Star Matter Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29143,
        Label = "Magmatter Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29588,
        Label = "SpaceTime Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29139,
        Label = "Universium Foil",
        Fluid = false,
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 14,
        ID = 2608,
        Label = "4x SpaceTime Wire",
        Fluid = false,
      },
      [11] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 8,
        ID = 4129,
        Label = "Neutronium Nanites",
        Fluid = false,
      },
      [12] = {
        Name = "{Fluid:molten.magnetohydrodynamicallyconstrainedstarmatter}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Magnetohydrodynamically Constrained Star Matter",
        Fluid = true,
      },
      [13] = {
        Name = "{Fluid:molten.spacetime}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten SpaceTime",
        Fluid = true,
      },
      [14] = {
        Name = "{Fluid:molten.universium}",
        Amount = 576,
        ID = 0,
        Label = "drop of Molten Universium",
        Fluid = true,
      },
      [15] = {
        Name = "{Fluid:molten.mutatedlivingsolder}",
        Amount = 14400,
        ID = 0,
        Label = "drop of Mutated Living Solder",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (UXV)",
    ID = 32039,
  },
}