return {
  conveyormodulezpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32607,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (ZPM)",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17325,
        Amount = 2,
        Fluid = false,
        Label = "Naquadah Alloy Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28325,
        Amount = 4,
        Fluid = false,
        Label = "Naquadah Alloy Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25325,
        Amount = 32,
        Fluid = false,
        Label = "Naquadah Alloy Round",
      },
      [5] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1748,
        Amount = 2,
        Fluid = false,
        Label = "4x Vanadium-Gallium Cable",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17471,
        Amount = 20,
        Fluid = false,
        Label = "Silicone Rubber Sheet",
      },
      [7] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 288,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [8] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 750,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Conveyor Module (ZPM)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32636,
  },
  electricmotorzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 23399,
        Amount = 2,
        Fluid = false,
        Label = "Magnetic Samarium Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22325,
        Amount = 4,
        Fluid = false,
        Label = "Long Naquadah Alloy Rod",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28325,
        Amount = 4,
        Fluid = false,
        Label = "Naquadah Alloy Ring",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 25325,
        Amount = 16,
        Fluid = false,
        Label = "Naquadah Alloy Round",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1748,
        Amount = 2,
        Fluid = false,
        Label = "4x Vanadium-Gallium Cable",
      },
      [9] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 288,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [10] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 750,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Motor (ZPM)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32607,
  },
  electricpumpzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32607,
        Amount = 1,
        Fluid = false,
        Label = "Electric Motor (ZPM)",
      },
      [2] = {
        Name = "gregtech:gt.blockmachines",
        ID = 5192,
        Amount = 2,
        Fluid = false,
        Label = "Enderium Fluid Pipe",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17325,
        Amount = 2,
        Fluid = false,
        Label = "Naquadah Alloy Plate",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 27325,
        Amount = 8,
        Fluid = false,
        Label = "Naquadah Alloy Screw",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 28471,
        Amount = 8,
        Fluid = false,
        Label = "Silicone Rubber Ring",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 21325,
        Amount = 2,
        Fluid = false,
        Label = "Naquadah Alloy Rotor",
      },
      [7] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1748,
        Amount = 2,
        Fluid = false,
        Label = "4x Vanadium-Gallium Cable",
      },
      [8] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 288,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [9] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 750,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Electric Pump (ZPM)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32616,
  },
  fieldgeneratorzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        ID = 325,
        Amount = 1,
        Fluid = false,
        Label = "Naquadah Alloy Frame Box",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 17325,
        Amount = 6,
        Fluid = false,
        Label = "Naquadah Alloy Plate",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32725,
        Amount = 2,
        Fluid = false,
        Label = "Quantum Star",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32686,
        Amount = 4,
        Fluid = false,
        Label = "Emitter (ZPM)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32094,
        Amount = 4,
        Fluid = false,
        Label = "Wetware Supercomputer",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [9] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 19070,
        Amount = 64,
        Fluid = false,
        Label = "Fine Europium Wire",
      },
      [10] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1748,
        Amount = 8,
        Fluid = false,
        Label = "4x Vanadium-Gallium Cable",
      },
      [11] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 1152,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
    },
    Label = "Field Generator (ZPM)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32676,
  },
  robotarmzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 22325,
        Amount = 4,
        Fluid = false,
        Label = "Long Naquadah Alloy Rod",
      },
      [2] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 31325,
        Amount = 1,
        Fluid = false,
        Label = "Naquadah Alloy Gear",
      },
      [3] = {
        Name = "gregtech:gt.metaitem.02",
        ID = 20325,
        Amount = 3,
        Fluid = false,
        Label = "Small Naquadah Alloy Gear",
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32607,
        Amount = 2,
        Fluid = false,
        Label = "Electric Motor (ZPM)",
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        ID = 32646,
        Amount = 1,
        Fluid = false,
        Label = "Electric Piston (ZPM)",
      },
      [6] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32090,
        Amount = 2,
        Fluid = false,
        Label = "Ultimate Crystalcomputer",
      },
      [7] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32096,
        Amount = 4,
        Fluid = false,
        Label = "Crystalprocessor Assembly",
      },
      [8] = {
        Name = "gregtech:gt.metaitem.03",
        ID = 32089,
        Amount = 8,
        Fluid = false,
        Label = "Crystalprocessor",
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        ID = 1748,
        Amount = 6,
        Fluid = false,
        Label = "4x Vanadium-Gallium Cable",
      },
      [10] = {
        Name = "{Fluid:molten.indalloy140}",
        ID = 0,
        Amount = 1152,
        Fluid = true,
        Label = "drop of Molten Indalloy 140",
      },
      [11] = {
        Name = "{Fluid:lubricant}",
        ID = 0,
        Amount = 750,
        Fluid = true,
        Label = "drop of Lubricant",
      },
    },
    Label = "Robot Arm (ZPM)",
    Name = "gregtech:gt.metaitem.01",
    ID = 32656,
  },
  sensorzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 325,
        Label = "Naquadah Alloy Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32607,
        Label = "Electric Motor (ZPM)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 17317,
        Label = "Osmiridium Plate",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32725,
        Label = "Quantum Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32090,
        Label = "Ultimate Crystalcomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1748,
        Label = "4x Vanadium-Gallium Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 1152,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Sensor (ZPM)",
    ID = 32696,
  },
  emitterzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.blockframes",
        Amount = 1,
        ID = 325,
        Label = "Naquadah Alloy Frame Box",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32607,
        Label = "Electric Motor (ZPM)",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 8,
        ID = 23317,
        Label = "Osmiridium Rod",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 2,
        ID = 32725,
        Label = "Quantum Star",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.03",
        Amount = 4,
        ID = 32090,
        Label = "Ultimate Crystalcomputer",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 64,
        ID = 29868,
        Label = "Trinium Foil",
        Fluid = false,
      },
      [9] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 7,
        ID = 1748,
        Label = "4x Vanadium-Gallium Cable",
        Fluid = false,
      },
      [10] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 1152,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Emitter (ZPM)",
    ID = 32686,
  },
  electricpistonzpm = {
    recipe = {
      [1] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 1,
        ID = 32607,
        Label = "Electric Motor (ZPM)",
        Fluid = false,
      },
      [2] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 6,
        ID = 17325,
        Label = "Naquadah Alloy Plate",
        Fluid = false,
      },
      [3] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 28325,
        Label = "Naquadah Alloy Ring",
        Fluid = false,
      },
      [4] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 32,
        ID = 25325,
        Label = "Naquadah Alloy Round",
        Fluid = false,
      },
      [5] = {
        Name = "gregtech:gt.metaitem.01",
        Amount = 4,
        ID = 23325,
        Label = "Naquadah Alloy Rod",
        Fluid = false,
      },
      [6] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 1,
        ID = 31325,
        Label = "Naquadah Alloy Gear",
        Fluid = false,
      },
      [7] = {
        Name = "gregtech:gt.metaitem.02",
        Amount = 2,
        ID = 20325,
        Label = "Small Naquadah Alloy Gear",
        Fluid = false,
      },
      [8] = {
        Name = "gregtech:gt.blockmachines",
        Amount = 4,
        ID = 1748,
        Label = "4x Vanadium-Gallium Cable",
        Fluid = false,
      },
      [9] = {
        Name = "{Fluid:plasma.molten.indalloy140}",
        Amount = 288,
        ID = 0,
        Label = "drop of Molten Indalloy 140",
        Fluid = true,
      },
      [10] = {
        Name = "{Fluid:plasma.lubricant}",
        Amount = 750,
        ID = 0,
        Label = "drop of Lubricant",
        Fluid = true,
      },
    },
    Name = "gregtech:gt.metaitem.01",
    Label = "Electric Piston (ZPM)",
    ID = 32646,
  },
}